service: makeupiv

provider:
  name: aws
  runtime: ruby2.7
  memorySize: 128
  region: eu-west-3
  stage: dev

functions:
  misdatospersonales:
    handler: handler.misdatospersonales
    description: "Muestra mis datos personales de MakeupIV"
    events:
      - http:
          path: /
          method: post
    environment:
        TG_TOKEN: ${ssm:makeupiv-token~true}
plugins:
  - serverless-hooks-plugin

custom:
  hooks:
    package:initialize:
      -bundle install --deployment
